version: '3.7'
services:
  postgres:
    image: marcosfede/farmaciasdeturno-postgres:develop
    build: './packages/postgres'
    ports:
      - '5432:5432'
    volumes:
      - db_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'

  front:
    image: marcosfede/farmaciasdeturno-client:develop
    build:
      context: './packages/client'
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./packages/client:/app:cached
      - nm_front:/app/node_modules

  back:
    image: marcosfede/farmaciasdeturno-back:develop
    depends_on:
      - postgres
    build: './packages/server'
    ports:
      - '4000:3000'
    command: 'yarn start:dev'
    volumes:
      - ./packages/server:/app:delegated
      - nm_back:/app/node_modules

  scrapper:
    image: marcosfede/farmaciasdeturno-scrapper:develop
    build: './packages/scrapper'
    command: 'npm run run:dev'

volumes:
  db_dev:
  nm_front:
  nm_back:
