version: '3'
services:
  postgres:
    build: './packages/postgres'
    ports:
      - '5432:5432'
    volumes:
      - db_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'

  client:
    build:
      context: './packages/client'
      dockerfile: 'Dockerfile'
    ports:
      - '8000:8000'
    volumes:
      - ./packages/client:/app:cached
      - /app/node_modules
    command: 'npm run develop -- --host 0.0.0.0'

  back:
    depends_on:
      - postgres
    build: './packages/server'
    ports:
      - '4000:3000'
    command: 'yarn start:dev'
    volumes:
      - ./packages/server:/app:delegated
      - /app/node_modules

  scrapper:
    build: './packages/scrapper'
    command: 'npm run run:dev'

volumes:
  db_dev:
