version: '3'
services:
  postgres:
    build: './packages/postgres'
    ports:
      - '5432:5432'
    volumes:
      - db_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'

  scrapper:
    build: './packages/scrapper'
    command: 'npm run run:dev'

volumes:
  db_dev:
