version: '3'
services:
  postgres:
    build: './packages/postgres'
    ports:
      - '5432:5432'
    volumes:
      - db_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'

  # client:
  #   build:
  #     context: './packages/client'
  #     dockerfile: 'Dockerfile'
  #     args:
  #       - REACT_APP_API_URL=http://localhost:4000
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./client:/app:delegated
  #     - /app/node_modules
  #   command: 'yarn start'

  # back:
  #   depends_on:
  #     - postgres
  #   build: './packages/server'
  #   ports:
  #     - '4000:3000'
  #   command: 'yarn start:dev'
  #   volumes:
  #     - ./packages/server:/app:delegated
  #     - /app/node_modules

  # scrapper:
  #   build: './packages/scrapper'
  #   command: 'npm run run:dev'

volumes:
  db_dev:
